---
- name: Configure Jenkins Containers on Ubuntu Server
  hosts: aws
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - git
          - docker.io
          - maven
          - mysql-server
          - apache2
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Start and enable Apache2 service
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes
